### ISSUE TITLE
Running Experiments in On-Robot Learning With Equivariant Models on UR5 robot

### ISSUE THREAD

**Issue by ZJU-PLP** [pointW/equi_rl#2]
@pointW 

Hi, Dian:

I meet the error when to Running Equivariant SAC with Group D4 on UR5 robot. Would you mind sharing the training and test details  on UR5 robot?

**Command:**
`python main.py --env=close_loop_block_picking --num_processes=1 --robot=ur5 --workspace_size=0.3 --view_type=render_center --transparent_bin=f --max_train_step=10000 --max_episode_steps=50 --planner_episode=20 --dpos=0.05 --drot_n=4 --alg=sac --model=equi_both_d --equi_n=4 --batch_size=64 --buffer=aug --lr=1e-3 --gamma=0.99 --eval_freq=-1`

**Error:**
  `AttributeError: 'UR5_Simple' object has no attribute 'getGripperOpenRatio'`

**Comment by pointW** [comment]
Hi Linpeng,

Do you want to run the code with a real robot? Unfortunately, this repo only contains the code for the simulation experiments, which was using a panda arm instead of a UR5 arm. So you would need to change `--robot=ur5` into `--robot=panda` in your command. If you want to run the algorithm on a real UR5 robot, you would need to setup the robot environment manually.

**Comment by ZJU-PLP** [comment]
> Hi Linpeng,
> 
> Do you want to run the code with a real robot? Unfortunately, this repo only contains the code for the simulation experiments, which was using a panda arm instead of a UR5 arm. So you would need to change `--robot=ur5` into `--robot=panda` in your command. If you want to run the algorithm on a real UR5 robot, you would need to setup the robot environment manually.

Yes, I want to run the code with my ur5 real robot. Before running on the real robot, I want to reproduce the code on the ur5 simulation  environment . However, following your advice, I must setup up ur5 simulation  environment, that's right?  Whether the code of ur5_simple.py in [here](https://github.com/pointW/helping_hands_rl_envs/blob/0e8fe1cd2cb286518ff6a487eda23a817e3f420d/helping_hands_rl_envs/pybullet/robots/ur5_simple.py) can be used in your released version?

**Comment by pointW** [comment]
Hi Linpeng, please note that the simulation experiment in the paper is performed using a **panda** arm instead of a **ur5** arm. I encourage you to run the simulation experiment using the panda arm or the kuka arm because the ur5 robot in our simulator is not as stable as the other two. 

If you want to run the code in the real world, you would need to construct a real-world environment.

**Comment by ZJU-PLP** [comment]
> Hi Linpeng, please note that the simulation experiment in the paper is performed using a **panda** arm instead of a **ur5** arm. I encourage you to run the simulation experiment using the panda arm or the kuka arm because the ur5 robot in our simulator is not as stable as the other two.
> 
> If you want to run the code in the real world, you would need to construct a real-world environment.

Ok, I see. Thanks for your reply.
